### PR TITLE
tests: fix broken tests and switch CI runner to GitHub Actions

### PR DESCRIPTION
**Pull request by stvnjacobs**
Hey @ssplatt. Hope you are doing well.

A couple years ago, support for [version 4 of the Linode API](https://www.linode.com/docs/api) was added to fog through [`fog-linode`](https://github.com/fog/fog-linode). I have had it on the back-burner to get `kitchen-linode` updated to use it for some time now.

Before taking that on, I wanted to get tests passing  locally and in CI with the current version. That work is included in this PR. I tried to group each commit with a short description of the reason for the change. Please let me know if there are any questions.

Notable changes are:
- Switch from Travis to GitHub Actions. With the ease of adding GitHub Actions here, I thought it made sense.
- ~Removal of Code Climate. I did not have an account and was not able to test it.~
- Removal of Tailor. It is an archived project that was causing issues. An updated rubocop config should provide similar value. The same goes for cane, but Cane was working as intended so I left it.

### CODE REVIEW

**Comment by stvnjacobs** [comment]
I opened a PR on my fork to trigger the GitHub Action runs, here:
https://github.com/stvnjacobs/kitchen-linode/pull/1/checks

**Comment by ssplatt** [comment]
Maybe keep codeclimate. It's still free for open source projects, no?

**Comment by stvnjacobs** [comment]
I confirmed it is free for open source and added code coverage reporting in this most recent commit. The workflow is a bit more repetitive than I would like, but after searching GitHub for other implementations, I dislike this one the least.

**Comment by stvnjacobs** [comment]
It looks like we were not reporting code coverage previously. It would simplify things a bit to leave it out. Let me know if you think it is valuable enough to keep.

**Comment by stvnjacobs** [comment]
In case you want to review, here is what Code Climate looks like with coverage reporting.
https://codeclimate.com/github/stvnjacobs/kitchen-linode

**Review by ssplatt — APPROVED** [review]
👍

**Pull request merged**
